version: "3.9"
services:
  llm_app:
    build: .
    container_name: llm_portfolio
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
